- name: Create consul user
  user:
    name: consul
    shell: /usr/bin/false
    create_home: yes
    home: /opt/consul

- name: Check if consul binary already exists
  stat:
    path: /opt/consul/consul
  register: consul_binary

- name: Download consul binary
  unarchive:
    src: https://releases.hashicorp.com/consul/1.7.4/consul_1.7.4_linux_amd64.zip
    dest: /opt/consul/
    remote_src: yes
  when: not consul_binary.stat.exists

- name: Link consul binary
  file:
    src: /opt/consul/consul
    dest: /usr/bin/consul
    owner: root
    state: link

- name: Create consul config directory
  file:
    path: /etc/consul
    state: directory

- name: Create consul config
  template:
    src: consul.hcl.j2
    dest: /etc/consul/consul.hcl

- name: Create consul data directory
  file:
    path: /var/lib/consul
    owner: consul
    group: consul
    state: directory

- name: Create consul systemd service
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service

- name: Enable and start consul service
  systemd:
    name: consul.service
    daemon_reload: yes
    enabled: yes
    state: restarted
