- name: Create consul user
  user:
    name: consul
    shell: /usr/bin/false
    create_home: yes
    home: /opt/consul

- name: Create consul directory
  file:
    path: "/opt/consul/{{ consul_version }}"
    state: directory

- name: Download consul binary
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: "/opt/consul/{{ consul_version }}/consul.zip"
    checksum: "sha256:{{ consul_checksum }}"

- name: Extract consul binary
  unarchive:
    src: "/opt/consul/{{ consul_version }}/consul.zip"
    dest: "/opt/consul/{{ consul_version }}"
    creates: "/opt/consul/{{ consul_version }}/consul"
    remote_src: yes

- name: Link consul binary
  file:
    src: "/opt/consul/{{ consul_version }}/consul"
    dest: /usr/bin/consul
    owner: root
    state: link

- name: Create consul config directory
  file:
    path: /etc/consul
    state: directory

- name: Create consul config
  template:
    src: consul.hcl.j2
    dest: /etc/consul/consul.hcl

- name: Create consul data directory
  file:
    path: /var/lib/consul
    owner: consul
    group: consul
    state: directory

- name: Create consul systemd service
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service

- name: Enable and start consul service
  systemd:
    name: consul.service
    daemon_reload: yes
    enabled: yes
    state: restarted
