- name: Reject everything and enable UFW
  ufw:
    state: enabled
    policy: reject
    log: yes

- name: Allow SSH
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow OpenVPN
  ufw:
    rule: allow
    port: '1194'
    proto: udp
  when: openvpn_server

- name: Allow http and https
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - '80'
    - '443'

- name: Allow everything in private network
  ufw:
    rule: allow
    src: "{{ private_network_cidr }}"
    dest: "{{ private_network_cidr }}"

- name: Allow docker network to some ports
  ufw:
    rule: allow
    src: 172.17.0.1/16
    dest: "{{ private_network_ip }}"
