- name: Enable UFW and logging
  ufw:
    state: enabled
    logging: low

- name: Reject incoming by default
  ufw:
    direction: incoming
    policy: reject

- name: Allow outgoing by default
  ufw:
    direction: outgoing
    policy: allow

- name: Allow routed by default
  ufw:
    direction: routed
    policy: allow

- name: Allow SSH
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow http and https
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - '80'
    - '443'

- name: Allow everything in private network
  ufw:
    rule: allow
    src: "{{ private_network_cidr }}"
    dest: "{{ private_network_cidr }}"

- name: Allow docker network to some ports in private interface
  ufw:
    rule: allow
    src: 172.17.0.1/16
    dest: "{{ private_network_ip }}"
    port: "{{ item }}"
  with_items:
    - '53'
