- name: Machine upgrade
  become: yes
  hosts: all
  serial: 1
  tasks:
    - name: Run apt upgrade
      apt:
        update_cache: yes
        upgrade: dist
    - name: Clean packages
      apt:
        autoclean: yes
        autoremove: yes
    - name: Reboot machine
      reboot: {}
