- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Install dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Start dnsmasq service
  systemd:
    name: dnsmasq
    enabled: true
    state: restarted

- name: Forward systemd query to dnsmasq
  copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf

- name: Restart systemd resolved
  service:
    name: systemd-resolved
    state: restarted
