name: Infra Spec

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_spec:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: |
          gem install bundler
          bundle install
          bundle exec rspec --format documentation
